/**
 * In-app orientation content, tailored per role. Mirrors the onboarding
 * manual but lives inside the product so every user has a Help section that
 * speaks to what they actually do.
 */
export type Guide = {
  eyebrow: string;
  title: string;
  who: string;
  lands: string;
  steps: string[];
  tips: string[];
  cannot: string;
};

const GUIDES: Record<string, Guide> = {
  firm: {
    eyebrow: "Firm operations",
    title: "Owner and Firm Admin",
    who: "You run the practice: configure the workspace, build the team, watch the numbers and keep cases moving.",
    lands: "/firm",
    steps: [
      "Read the dashboard first: deadlines in the next 14 days and high-risk cases are surfaced up top.",
      "Open Leads to work the commercial pipeline, from new lead to signed engagement.",
      "Add a client in Clients, then open a case in Cases. The document checklist is generated automatically.",
      "Scan Documents, Partners, Billing and Compliance to see the whole operation at a glance.",
    ],
    tips: [
      "Use the dashboard as your daily standup: critical deadlines and risk before anything else.",
      "Keep commercial notes separate from legal notes. The lead pipeline is commercial; case strategy stays protected.",
      "The compliance calendar is where recurring revenue lives: renewals, expirations and corporate obligations.",
    ],
    cannot: "The owner does not create legal strategy or send opinions. That is the attorney's role. You run the operation; the attorney owns the merits.",
  },
  attorney: {
    eyebrow: "Legal lead",
    title: "Attorney",
    who: "You are legally responsible for the case. Nothing final leaves without your approval. You set strategy, review evidence and sign the gates.",
    lands: "/firm",
    steps: [
      "Open a case in Cases (try the demo case MIL-2026-0001, an E-2).",
      "Read status, risk, progress, team, next action and deadline at the top. Open risks appear in a red block.",
      "Review the checklist and documents. Approve, reject or request changes. A rejected document returns to the client with the reason.",
      "Record private legal notes with visibility 'Legal team' or 'Attorney only'. Clients and partners never see these.",
      "Use the approval gates: strategy, documents complete, petition draft, filing ready.",
      "Moving a case to Filing ready requires an approved filing gate. If you may approve, the move itself records the approval.",
    ],
    tips: [
      "Treat the gates as your accountability trail: each decision is stored with author and date.",
      "Use the Internal channel to align with the paralegal without the client seeing.",
      "The AI can summarize and flag inconsistencies, but every route suggestion stays a draft until you review it. It never changes status or sends a document.",
    ],
    cannot: "You do not need to handle document collection yourself. Delegate to the paralegal and case manager and focus on the merits.",
  },
  paralegal: {
    eyebrow: "Operational engine",
    title: "Paralegal",
    who: "You keep the case moving: collect documents, organize tasks and prepare drafts for the attorney to decide on.",
    lands: "/firm",
    steps: [
      "Open a case and read the checklist generated by the visa category. Each item has an owner and a status.",
      "Upload documents per checklist item. The item moves to Uploaded and enters the attorney review queue.",
      "Create tasks for the client, colleagues and partners, with an owner and a due date.",
      "Use the Operational and Internal channels. You can read the internal channel.",
      "Follow the timeline: everything that happens in the case is recorded there.",
    ],
    tips: [
      "You can suggest a review outcome; the final approval is the attorney's. Leave items ready for a one-click confirm.",
      "You see 'Legal team' notes, not 'Attorney only' ones. Use them to orient yourself without touching what is restricted.",
    ],
    cannot: "You do not create legal strategy, do not give final document approval and do not sign the filing gates.",
  },
  client: {
    eyebrow: "Principal applicant",
    title: "Client",
    who: "The person going through the visa process. The portal is built for you to understand your case without legal jargon.",
    lands: "/client",
    steps: [
      "On My Case, see your stage, progress, next action, deadline and who is currently responsible.",
      "In Documents, upload each requested file. PDF, JPG, PNG or DOCX up to 20MB. If one is rejected, the reason appears.",
      "In Tasks, see what the team asked and mark it done.",
      "In Messages, talk to your team. Payments shows invoices; Timeline shows the whole process.",
    ],
    tips: [
      "Whenever you see 'Action needed' or 'Waiting for your documents', you are the one responsible. Solving it fast speeds everything up.",
      "You always see the status in plain language, not the technical view the firm uses.",
    ],
    cannot: "You do not see private legal notes or internal team conversations. That is normal and protects the strategy of your own case.",
  },
  partner: {
    eyebrow: "External professional",
    title: "Partner",
    who: "You are hired for a specific deliverable on a case (a CPA report, a business plan, a translation, an appraisal).",
    lands: "/partner",
    steps: [
      "In Assigned Tasks, see the tasks in your scope. Each block shows the case, the scope and the access window if any.",
      "Upload your deliverable straight onto the task and mark it complete.",
      "In Documents shared with me, track only the files you uploaded.",
    ],
    tips: [
      "Your access is deliberate and limited. You never see the whole case or the other partners, and that protects the client and you.",
      "If your access has an expiry, deliver within the window.",
    ],
    cannot: "You do not see the full case dossier, legal notes, other partners' data or anything outside your scope.",
  },
  admin: {
    eyebrow: "Platform",
    title: "Super Admin",
    who: "You administer the whole platform, above the firms. Every action you take is audited.",
    lands: "/admin",
    steps: [
      "On the overview, track active tenants, case and document volume and the count of AI requests blocked by the legal-advice guardrail.",
      "In Tenants, see each firm with its numbers. Data is isolated per tenant.",
      "In Users, create accounts, change roles and enable or disable people.",
      "In Visa Categories, manage the visa engine. In Audit Log, follow the immutable trail of sensitive actions.",
    ],
    tips: [
      "Use the audit log as your main governance and compliance tool.",
      "Editing a visa category affects the checklists of all new cases in that category.",
    ],
    cannot: "The super admin does not replace a case's attorney. You run the platform; the merits stay with the firm.",
  },
};

export function guideForRole(roleKey: string | null, isPlatformAdmin: boolean): Guide {
  if (isPlatformAdmin || roleKey === "super_admin") return GUIDES.admin;
  if (roleKey === "client") return GUIDES.client;
  if (roleKey === "partner") return GUIDES.partner;
  if (roleKey === "paralegal") return GUIDES.paralegal;
  if (roleKey === "attorney" || roleKey === "supervising_attorney") return GUIDES.attorney;
  return GUIDES.firm;
}

export const ALL_GUIDES = GUIDES;
